### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by saleyn** [JeffFlinn/boost-process#6]
How does this version relate to this boost-process?
http://www.highscore.de/boost/process0.5/

Which one is newer?

**Comment by JeffFlinn** [comment]
This project is closer to the original presentation at boostcon a few years ago. Boris' still suffers IMO from lack of portability with the need for #ifdef in client code, but may be chronologically newer. I need to review/merge Christian's Leutlof's commits supporting environment variables. Also Boris' version handles async waiting for child process exit.

This is version is used in at least a couple of commercial applications that run portably on Windows and Mac systems.

Let me know if that helps.

Jeff

**Comment by JeffFlinn** [comment]
Serge,

This project is closer to the original presentation at boostcon a few years
ago. Boris' still suffers IMO from lack of portability with the need for
#ifdef in client code, but may be chronologically newer. I need to
review/merge Christian's Leutlof's commits supporting environment
variables. Also Boris' version handles async waiting for child process exit.

This is version is used in at least a couple of commercial applications
that run portably on Windows and Mac systems.

Let me know if that helps.

Jeff

**Comment by saleyn** [comment]
Thanks!
